-- Criação da tabela de análises
CREATE TABLE ANALISE_SOLO (
    id_analise NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cultura VARCHAR2(50) NOT NULL,
    nitrogenio NUMBER(5,2),
    fosforo NUMBER(5,2),
    potassio NUMBER(5,2),
    ph NUMBER(4,2),
    status VARCHAR2(20),
    recomendacao VARCHAR2(500),
    data_analise TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);